repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
          - --args=-write=false
      - id: terraform_validate
        args:
          - --args=-no-color
        exclude: |
          (?x)^(
            .*examples/.*
          )$
      - id: terraform_checkov
        args:
          - --args=--check
          - --args=CKV_CLOUDFLARE_*
          - --args=--check
          - --args=CKV_*
          - --args=--skip-check
          - --args=CKV_123
          - --args=--skip-check
          - --args=CKV_124
          - --args=--skip-check
          - --args=CKV_SECRET_6
          - --args=--compact
          - --args=--quiet
          - --args=--directory
          - --args=.
        exclude: |
          (?x)^(
            .*terraform\.tfvars\.json$
            .*examples/.*
          )$
      